select*  from customer limit 5
# Q1.What is the total revenue generated by male vs. female customer?
select gender,SUM(purchase_amount_) as Revenue
from customer
group by gender

#  Q2.which customer used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount_
from customer
where discount_applied='YES' and purchase_amount_ >= (select AVG(purchase_amount_) from customer)

# Q3.Which are the top 5 product with the highest average review  rating?
SELECT item_purchased,
       ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))), 2) AS 'Average_Product_Rating'
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

# Q4.Compare the average purchase amount between Standard and express Shipping
select shipping_type,ROUND(AVG(purchase_amount_),2) as 'average purchase amount'
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

# Q5.Do Subscribed customer spend more? Compare average and total revenue between subscribers and non-subscribers
select subscription_status,COUNT(customer_id) as total_customers,ROUND(AVG(purchase_amount_),2) as avg_spend,ROUND(SUM(purchase_amount_),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc

# Q6.Which product have the  highest percentage of  purchase with discounts applied?
SELECT item_purchased,
       ROUND(SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

# Q7.Segment customer into new,returning and loyal on their total number of previous purchases,and show the count of each segment 
with customer_type as(
select customer_id,previous_purchases,
CASE
	WHEN previous_purchases=1 THEN 'New' 
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
    END as customer_segment
from customer
)
select customer_segment,count(*)  as 'Number of Customer'
from customer_type
group by customer_segment

# Q8.what are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

# Q9.are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

# Q10.what is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount_) as total_revenue
from customer
group by age_group
order by total_revenue desc;